name: "🔬 Fetch Cell API and Save to SQLite"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      # 1. Unduh repositori ke komputer virtual Ubuntu
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Siapkan Python versi terbaru (Hapus baris cache: 'pip' untuk mengatasi eror)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Pasang dependensi HTTP Request langsung via pip terminal
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Jalankan script Python untuk menembak API dan membuat database SQLite
      - name: Execute Sync Script
        run: |
          python database.py

      # 5. Unggah file hasil jadinya (.db) ke server GitHub sebagai Artifacts
      - name: Upload Database Artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-api-cells-database
          path: sel_manusia.db
