name: Tarik Harga Harian Per Menit

on:
# schedule:
#    - cron: '30 09 * * 1-5'   # UTC 09:30 = WIB 16:30
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cek master_emiten.csv, buat jika tidak ada
        run: |
          if [ ! -f "data_saham/master_emiten.csv" ]; then
            echo "⚠️ master_emiten.csv tidak ditemukan, jalankan tarik_emiten..."
            python core/tarik_emiten.py
          fi

      - name: Jalankan script tarik_harga_harian
        run: python core/tarik_harga_harian.py

      - name: Commit & push file Parquet baru
        run: |
          git config user.name "NadiWarnadi"
          git config user.email "warnadi2006@gmail.com"
          git add data_saham/tahun=*/harga_*.parquet
          git diff --cached --quiet || git commit -m "Update harga harian $(date +'%Y-%m-%d')"
          git push
